variables:
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'Bicep-l0204-RG' # Needs to already exist
  location: 'eastus'
  templateFile: './main.bicep'
  sourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'

trigger:
- none

pool:
  vmImage: $(vmImageName)

name: Bicep deploy template

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '3fc69942-82b4-4504-a8ab-50f941d0bdd9'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az deployment group create --resource-group $(resourceGroupName) --template-file $(sourceFolder)$(templateFile) \
      --parameters administratorLogin=$(administratorLogin) administratorLoginPassword=$(administratorLoginPassword)
